#!/bin/bash

# Privileged ESP scan for the GUI's OS detection.
#
# Detection runs unprivileged, but systemd-gpt-auto-generator mounts ESPs
# dmask=0077 root:root (the Steam Deck's /esp is drwx------ root root), so an
# unprivileged scan sees nothing and silently reports no OSes. The GUI already
# recovers SteamOS/Windows from the firmware's boot variables without a
# password; this script covers what those miss - a loader present on the ESP
# with no EFI boot entry pointing at it.
#
# Writes a cache the GUI reads on its next detect, keyed by partition GUID:
#   [b9beb192-116a-4bd2-8f09-5c703af03a5f]
#   /EFI/steamos/steamcl.efi
#
# Invoked from the GUI's Deep Scan button; safe to run standalone.

ESP_GUID="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
CACHE="$HOME/.local/SteamDeck_rEFInd/GUI/esp_scan.conf"

# Enumerate mounted ESPs unprivileged - findmnt/lsblk read metadata, not the
# filesystem contents, so they work fine without root. Devices come from lsblk
# (device paths never contain spaces) and each mount point from a plain
# findmnt -no (no -r: that escapes spaces as \x20, which find would then take
# literally). The pairs are passed to root as positional parameters — never
# splice filesystem-derived strings into a shell command line.
SCAN_ARGS=()
FOUND=0
while read -r dev; do
    [ -n "$dev" ] || continue
    target="$(findmnt -no TARGET -S "$dev" 2>/dev/null | head -1)"
    [ -n "$target" ] || continue
    partuuid="$(lsblk -no PARTUUID "$dev" 2>/dev/null)"
    [ -n "$partuuid" ] || continue
    FOUND=$((FOUND + 1))
    SCAN_ARGS+=("$partuuid" "$target")
done < <(lsblk -rno PATH,PARTTYPE 2>/dev/null \
    | awk -v t="$ESP_GUID" '$2==t {print $1}')

if [ "$FOUND" -eq 0 ]; then
    zenity --error --title="No ESP found" \
        --text="No mounted EFI System Partition was found to scan." --width=400 2>/dev/null
    exit 1
fi

mkdir -p "$(dirname "$CACHE")"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
    echo "# SteamDeck_rEFInd ESP scan"
    echo "# Regenerated by scripts/scan_esp.sh. Safe to delete; the GUI falls"
    echo "# back to the firmware's boot entries without it."
} > "$TMP"

# Single sudo invocation so the user is prompted once for all ESPs. The
# payload sees only positional (partuuid, mountpoint) pairs.
# -maxdepth 4 covers /EFI/<vendor>/<subdir>/<loader>.efi (Microsoft nests
# bootmgfw.efi one level deeper than everyone else).
read -r -d '' SCAN_PAYLOAD <<'EOS'
while [ "$#" -ge 2 ]; do
    printf '[%s]\n' "$1"
    find "$2/EFI" -maxdepth 4 -iname '*.efi' -printf '/EFI/%P\n' 2>/dev/null | sort
    shift 2
done
EOS
if ! zenity --password --title="Enter sudo password" 2>/dev/null \
        | sudo -S bash -c "$SCAN_PAYLOAD" bash "${SCAN_ARGS[@]}" >> "$TMP" 2>/dev/null; then
    zenity --error --title="Scan failed" \
        --text="$(printf "Could not read the EFI System Partition.\nIncorrect sudo password, or the prompt was cancelled.")" \
        --width=450 2>/dev/null
    exit 1
fi

# A run that authenticated but found no loaders would otherwise overwrite a
# good cache with an empty one.
if ! grep -q '^/EFI/' "$TMP"; then
    zenity --error --title="Scan found nothing" \
        --text="$(printf "The EFI System Partition was read, but no .efi loaders were found.\nThe existing scan cache has been left untouched.")" \
        --width=500 2>/dev/null
    exit 1
fi

mv -f "$TMP" "$CACHE"
trap - EXIT

COUNT="$(grep -c '^/EFI/' "$CACHE")"
zenity --info --title="Scan complete" \
    --text="$(printf "Found %s EFI loader(s) across %s EFI System Partition(s).\nPress Rescan in the GUI to pick up the results." "$COUNT" "$FOUND")" \
    --width=500 2>/dev/null
